dist: trusty

sudo: false

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - os: osx
      compiler: gcc
  
    - os: osx
      compiler: clang
before_script:
  - eval "${MATRIX_EVAL}"

script: ./build/all.sh

notifications:
  recipients:
    - support@corvusoft.co.uk
  email:
    on_success: change
    on_failure: always
